export default [
  {
    id: 1,
    title: "headings",
    description: "Create clear heading hierarchy.",
    image: "/assets/guide/heading.gif",
    alt: "Changing text into a heading in the editor",
    timeoutMs: 14800,
  },
  {
    id: 2,
    title: "decorations",
    description: "Apply text formatting from the toolbar.",
    image: "/assets/guide/decorations.gif",
    alt: "Applying text decorations from the editor toolbar",
    timeoutMs: 14300,
  },
  {
    id: 3,
    title: "links",
    description: "Add links to selected text.",
    image: "/assets/guide/links.gif",
    alt: "Adding a hyperlink to selected text in the editor",
    timeoutMs: 13700,
  },
  {
    id: 4,
    title: "effects",
    description: "Remove formatting from selected text.",
    image: "/assets/guide/remove-effects.gif",
    alt: "Removing formatting effects from selected text",
    timeoutMs: 17700,
  },
  {
    id: 5,
    title: "tables",
    description: "Organize content with tables.",
    image: "/assets/guide/tables.gif",
    alt: "Creating and editing a table inside the editor",
    timeoutMs: 21600,
  },
  {
    id: 6,
    title: "autocomplete",
    description: "Continue writing with autocomplete suggestions.",
    image: "/assets/guide/autocomplete.gif",
    alt: "Using an autocomplete suggestion while writing",
    timeoutMs: 12900,
  },
  {
    id: 7,
    title: "images",
    description: "Insert images into your article.",
    image: "/assets/guide/images.gif",
    alt: "Inserting an image into the editor",
    timeoutMs: 10200,
  },
  {
    id: 8,
    title: "markdown",
    description: "Switch between rich text and Markdown.",
    image: "/assets/guide/markdown.gif",
    alt: "Switching between rich text editing and Markdown mode",
    timeoutMs: 12200,
  },
] as const;
